alertmanager:
  config:
    global:
      resolve_timeout: 5m

    route:
      group_by: ["alertname", "namespace"]
      group_wait: 30s
      group_interval: 1m
      repeat_interval: 100m
      receiver: "teams"
      routes:
        - match:
            severity: critical
          receiver: "teams"
          continue: true
        - match:
            severity: warning
          receiver: "teams"

    receivers:
      - name: 'teams'
        webhook_configs:
          - url: 'http://prometheus-msteams.default.svc.cluster.local:2000/alertmanager'
            send_resolved: true


prometheus:
  prometheusSpec:
    alerting:
      alertmanagers:
        - namespace: default
          name: alertmanager-operated
          port: web